sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '8'

notifications:
  email:
    recipients:
      # replace with your e-mail
      - nnsceg@gmail.com
    on_success: never
    on_failure: always

# uncomment this if you want to use semantic-release
# branches:
#  except:
#    - /^v\d+\.\d+\.\d+$/

before_script:
  - npm prune
script:
  - npm run cover
after_success:
 - npm run report-coverage
# uncomment this if you want publish package to npm
#  - npm run semantic-release
