### Only for Docker
# sudo: required
# services:
#   - docker
### docker section end

language: node_js

cache:
  directories:
    - node_modules
node_js:
  - '10.12'

notifications:
  email:
    recipients:
      # replace with your e-mail
      - nnsceg@gmail.com
    on_success: never
    on_failure: always

# uncomment this if you want to use semantic-release
# branches:
#  except:
#    - /^v\d+\.\d+\.\d+$/

before_script:
  - npm prune
script:
  - npm run test:cover
  - npm run build
after_success:
  - cat coverage/lcov.info | node_modules/.bin/coveralls
# uncomment this if you want publish package to npm via semantic-release
#  - node_modules/.bin/semantic-release
